# Generated by Django 2.2.dev20180914183443 on 2018-10-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('address', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('location_name', models.TextField(blank=True, null=True)),
                ('date_of_event', models.DateTimeField(blank=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('unique_link', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('max_attendees', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('company_name', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_types_serviced', models.TextField(blank=True, null=True)),
                ('services_offered', models.TextField(blank=True, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileUploader.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('pictures', models.TextField(blank=True, null=True)),
                ('event_types_sponsored', models.TextField(blank=True, null=True)),
                ('location_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileUploader.Location')),
            ],
        ),
    ]
